### PR TITLE
Add support for Tornado 6

### PR DESCRIPTION
**Pull request by owais**
This PR adds support for Tornado 6 by conditionally using different
scope manager, context manager and tracing implementation depending
on the version of Tornado and Python being used.

It does not require existing users to change anything other than upgrade
to the latest version of this package.

This package used to use the TornadoScopeManager shipped by
opentracing-python. The scope manager used `tornado.stack_context`
which was deprecated in Tornado 5 and removed in Tornado 6. Tornado
now recommends using contextvars package introduced in Python3.7.
opentracing-python already provides a ContextVarsScopeManager that
builds on top of the contextvars package. It also implements
AsyncioScopeManager which builds on top of asyncio and falls back
on thread local storage to implement context propagation. We fallback on
this for Python 3.6 and older when using Tornado 6 and newer.

The package also had seen some decay and some tests were not passing.
This PR updates the test suite and unit tests to get them working again.

Changes this PR introduces:

- Default to ContextVarsScopeManager instead of TornadoScopeManager.
Fallback on TornadoScopeManager or AsyncioScopeManager based on the
Tornado and Python version.
- Added tox support to enable easier testing across Python and Tornado
versions.
- Updated travis config to work with tox environments. Now each travis
build will run tests on every supported python version in parallel. Each
parallel test will run all tests for all versions of tornado serially.
- The PR add some code that uses the new async/await syntax. Such code
is invalid for older versions of python. To make it works for all
versions, we conditionally import modules depending on the Python
interpreter version.
- To preserve backward compatibility and to keep using common code for
all tornado versions, we've added some noop implementations that are not
to be used with newer versions of tornado.
- `tornado.gen.coroutine` was deprecated in favour of async/await but we
still support it where we can. There is a bug in Tornado 6 that prevents
us from support the deprecated feature on Python3.7 with
ContextVarsScopeManager.
(https://github.com/tornadoweb/tornado/pull/2716)
- Python3.4 also does not pass the tests for `tornado.gen.coroutine` but
it is not a regression caused by this PR. Testing on master results in
the same behavior. For now, I've added skip markers to these tests on
Python3.4. If needed, we can look into supporting these in future in a
separate PR.

### CODE REVIEW

**Comment by alisonatwork** [comment]
Hi @owais, i'm curious why you closed this PR. Is this project not maintained by @carlosalberto any more?

**Comment by owais** [comment]
I don't remember closing this

**Comment by owais** [comment]
I don't remember closing this. Probably happened by accident but it does look like this is not being very actively maintained. I guess focus has shifted to OpenTelemetry. This would still be great for OpenTracing users as it won't be feasible for everyone to move to Otel for months still if not years.

**Comment by alisonatwork** [comment]
Same thing on our end. We'd love to use OpenTelemetry when it's ready, but we are using OpenTracing in production right now, and getting async/await support and modern Tornado into this project would be great. It would help keep aligned with work like this in main OpenTracing Python lib: https://github.com/opentracing/opentracing-python/pull/118

**Comment by alisonatwork** [comment]
@owais I noticed you have some docs for this as well on 8c1121015b917615464139f36ff10cca1bbf8664 - could you add that on this PR?

**Comment by owais** [comment]
I think I had added those docs for our SignalFx fork of the package. I might not remember correctly but I think those docs didn't apply to this package and would actually go away if this (and a subsequent PR to opentating-python) were merged.

**Review by laerte-gaivota — COMMENTED** [review]
I need of the PR to mine application.

**Comment by owais** [comment]
I don't need this anymore so closing. Anyone feel free to adopt the PR or copy/use the code in any way you want.

**Pull request closed without merging**
